const events = [
  {
    slug: "UG-Reality",
    date: "SEPTEMBER 14, 2023",
    title: "Event 1: UG Reality Show",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/UGReality/IMG_6444.JPG",
      "/../../EventsImages/UGReality/IMG_6468.JPG",
      "/../../EventsImages/UGReality/IMG_6470.JPG",
      "/../../EventsImages/UGReality/IMG_6485.JPG",
      "/../../EventsImages/UGReality/IMG_6519.JPG",
      "/../../EventsImages/UGReality/IMG_6537.JPG",
      "/../../EventsImages/UGReality/IMG_6543.JPG",
      "/../../EventsImages/UGReality/IMG_6552.JPG",
      "/../../EventsImages/UGReality/IMG_6578.JPG",
      "/../../EventsImages/UGReality/IMG_6590.JPG",
    ],
  },
  {
    slug: "MHAweekevent",
    date: "SEPTEMBER 14, 2023",
    title: "Event 1: MHA week event",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/MHAweekevent/IMG20230930182150.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_181626.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_182057.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_181456.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230928_231402.jpg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.48.22.jpeg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.49.53.jpeg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.49.55.jpeg",
    ],
  },
  {
    slug: "SuicidePreventionDay",
    date: "SEPTEMBER 14, 2023",
    title: "Event 1: Suicide Prevention Day",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/SuicidePreventionDay/IMG_20221109_120503_Greatness.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC00043.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09909.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09930.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09931.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09941.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09942.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09947.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09968.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09988.jpg",
    ],
  },
  {
    slug: "painting",
    date: "SEPTEMBER 14, 2023",
    title: "Event 1: Painting",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/Painting/p3e3.JPG",
      "/../../EventsImages/Painting/e4p4.JPG",
      "/../../EventsImages/Painting/p7e7.JPG",
      "/../../EventsImages/Painting/p5e5.JPG",
      "/../../EventsImages/Painting/p2e2.JPG",
      "/../../EventsImages/Painting/p1e.JPG",
    ],
  },
  {
    slug: "PGPHDEvents",
    date: "September 14, 2023",
    title: "Event 1: PG-PHD Events",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191301.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193453.jpg",
      "/../../EventsImages/PGPhdEvents/DSC00754.JPG",
      "/../../EventsImages/PGPhdEvents/DSC00817.JPG",
      "/../../EventsImages/PGPhdEvents/IMG_20220925_182257.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20220925_184849.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191341.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191707.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191752.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191853.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_192006.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_192046.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_192527.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193336.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193425.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193545.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193615.jpg",
    ],
  },
  {
    slug: "DepartmentalOrientation",
    date: "September 14, 2023",
    title: "Event 1:Departmental Orientations ",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/DepartmentalOrientation/EE/20221109_181057.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/20221109_181524.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/20221109_191948.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109181509.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109181757.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109182025.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109184344.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109190309.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109192605.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109193317.jpg",
      "/../../EventsImages/DepartmentalOrientation/AI/20221111_164926.jpg",
    ],
  },
];

export default events;
