const events = [
  {
    slug: "event-1",
    date: "September 14, 2023",
    title: "Event 1: Introduction to React",
    summary: "Join us for an introduction to React and its core concepts.afsdfsdaf fdsfsdfadsfsdfsdfasdf . Musical Empowerments timeline uses a similar slider framework where users can click the arrows to advance the content. Designed without images or visuals, this approach would work well for an organization that doesnt have a deep asset library.Musical Empowerments timeline uses a similar slider framework where users can click the arrows to advance the content. Designed without images or visuals, this approach would work well for an organization that doesnt have a deep asset library.",
    description:
      "Join us for an introduction to React and its core concepts.afsdfsdaf fdsfsdfadsfsdfsdfasdf . Musical Empowerments timeline uses a similar slider framework where users can click the arrows to advance the content. Designed without images or visuals, this approach would work well for an organization that doesnt have a deep asset library.Musical Empowerments timeline uses a similar slider framework where users can click the arrows to advance the content. Designed without images or visuals, this approach would work well for an organization that doesnt have a deep asset library.",
    images: [
      "https://picsum.photos/500",
      "https://picsum.photos/700",
      "https://picsum.photos/800",
      "https://picsum.photos/200",
      "https://picsum.photos/200",
    ],
  },
  {
    slug: "event-today",
    date: "September 14, 2023",
    title: "Event 1: Introduction to React",
    summary: "Join us for an introduction to React and its core concepts.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "https://picsum.photos/200",
      "https://picsum.photos/200",
      "https://picsum.photos/200",
    ],
  },
  {
    slug: "event-tomorrow",
    date: "September 14, 2023",
    title: "Event 1: Introduction to React",
    summary: "Join us for an introduction to React and its core concepts.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "https://picsum.photos/200",
      "https://picsum.photos/200",
      "https://picsum.photos/200",
    ],
  },
  {
    slug: "event-uesterv",
    date: "September 14, 2023",
    title: "Event 1: Introduction to React",
    summary: "Join us for an introduction to React and its core concepts.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "https://picsum.photos/200",
      "https://picsum.photos/200",
      "https://picsum.photos/200",
    ],
  },
  {
    slug: "event-sgsag",
    date: "September 14, 2023",
    title: "Event 1: Introduction to React",
    summary: "Join us for an introduction to React and its core concepts.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "https://picsum.photos/200",
      "https://picsum.photos/200",
      "https://picsum.photos/200",
    ],
  },
  {
    slug: "event-sgdsg",
    date: "September 14, 2023",
    title: "Event 1: Introduction to React",
    summary: "Join us for an introduction to React and its core concepts.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "https://picsum.photos/200",
      "https://picsum.photos/200",
      "https://picsum.photos/200",
    ],
  },
  {
    slug: "UG-Reality",
    date: "September 14, 2023",
    title: "Event 1: UG Reality Show",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/UGReality/IMG_6444.JPG",
      "/../../EventsImages/UGReality/IMG_6468.JPG",
      "/../../EventsImages/UGReality/IMG_6470.JPG",
      "/../../EventsImages/UGReality/IMG_6485.JPG",
      "/../../EventsImages/UGReality/IMG_6519.JPG",
      "/../../EventsImages/UGReality/IMG_6537.JPG",
      "/../../EventsImages/UGReality/IMG_6543.JPG",
      "/../../EventsImages/UGReality/IMG_6552.JPG",
      "/../../EventsImages/UGReality/IMG_6578.JPG",
      "/../../EventsImages/UGReality/IMG_6590.JPG",
    ],
  },
  {
    slug: "MHAweekevent",
    date: "September 14, 2023",
    title: "Event 1: MHA week event",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/MHAweekevent/IMG20230930182150.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_181626.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_182057.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_181456.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230928_231402.jpg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.48.22.jpeg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.49.53.jpeg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.49.55.jpeg",
    ],
  },
  {
    slug: "SuicidePreventionDay",
    date: "September 14, 2023",
    title: "Event 1: Suicide Prevention Day",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/SuicidePreventionDay/IMG_20221109_120503_Greatness.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC00043.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09909.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09930.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09931.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09941.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09942.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09947.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09968.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09988.jpg",
    ],
  },
  {
    slug: "painting",
    date: "September 14, 2023",
    title: "Event 1: Painting",
    summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    description: "Join us for an introduction to React and its core concepts.",
    images: [
      "/../../EventsImages/Painting/p3e3.JPG",
      "/../../EventsImages/Painting/e4p4.JPG",
      "/../../EventsImages/Painting/p7e7.JPG",
      "/../../EventsImages/Painting/p5e5.JPG",
      "/../../EventsImages/Painting/p2e2.JPG",
      "/../../EventsImages/Painting/p1e.JPG",
    ],
  },
];

export default events;
