const events = [
  {
    slug: "ArtTherapy",
    date: "October 19, 2023",
    title: "Art Therapy Workshop for World Mental Health Month at IITH",
    summary:
      'The Art Therapy Workshop, hosted by Sunshine, the Counseling Cell of IITH, was a resounding success. Participants engaged in a series of creative activities, including "Pass It Around", which promoted unity and diverse perspectives. The "Guided Imagery Technique" provided a unique opportunity to relax and reflect using the power of imagination, while "Mindful Eating" allowed attendees to connect with their senses and improve their relationship with food.This event, held on 19th October 2023, not only provided moments of tranquility and stress relief but also facilitated community connections within our diverse IITH community. No prior artistic talent was necessary for participation. Stay tuned for more enriching events with Sunshine. For inquiries, feel free to reach out to us.',
    images: [
      "/../../EventsImages/ArtTherapy/IMG_8381.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8376.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8365.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8382.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8391.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8393.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8398.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8399.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8400.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8401.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8402.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8404.jpg",
      "/../../EventsImages/ArtTherapy/IMG_8406.jpg",
    ],
  },
  {
    slug: "WorldMentalHealthDay",
    date: "October 17, 2023",
    title: "World Mental Health Day at IIT Hyderabad",
    summary:
      "Our recent 'World Mental Health Day' program, hosted by the Sunshine Counseling Cell at IIT Hyderabad, featured two impactful sessions. The first, Jacobson's Progressive Muscle Relaxation (JPMR), allowed participants to experience a 40-minute session aimed at reducing stress and anxiety through evidence-based relaxation techniques. The second, a 10-minute journal writing exercise, encouraged self-expression and reflection to enhance mental well-being. Held on 17th October 2023 at LH3, MSME Building, these events brought our community together to focus on mental health and unity. Special thanks to our dedicated student coordinators, Mr. Teja and Ms. Suvitti, for their valuable support. Stay tuned for more enriching events at the Sunshine Counseling Cell.",
    images: [
      "/../../EventsImages/WorldMentalHealthDay/IMG_8158.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8107.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8085.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8093.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8097.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8108.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8127.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8142.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8150.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8159.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8170.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8183.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8187.jpg",
      "/../../EventsImages/WorldMentalHealthDay/IMG_8207.jpg",
    ],
  },
  {
    slug: "RandomActOfKindness",
    date: "October 16 to 22, 2023",
    title: '"Random Act of Kindness" - Spreading Positivity at IITH',
    summary:
      "In our 'Random Act of Kindness' initiative, the IITH community came together to spread positivity through heartfelt letters of appreciation and encouragement. Participants, blindfolded and guided to randomly selected recipients, handed over their letters and tokens of appreciation. The event aimed to make someone's day brighter, regardless of their familiarity. Captured by our photography and video team, these acts of kindness beautifully embodied the spirit of unity and compassion at IITH. We extend our gratitude to all who participated and supported this initiative, making it a remarkable success. Stay tuned for more heartwarming events with the Sunshine Team at IITH.",
    images: [
      "/../../EventsImages/RandomActOfKindness/IMG_7707.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_8422.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_7681.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_7685.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_7697.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_7733.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_7741.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_8222.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_8261.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_8320.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_8429.jpg",
      "/../../EventsImages/RandomActOfKindness/IMG_8442.jpg",
    ],
  },
  {
    slug: "SunshineWorldMentalHealthDay",
    date: "October 10, 2023",
    title: "Sunshine's World Mental Health Day Program",
    summary:
      'Our World Mental Health Day Program, hosted by Sunshine - The Counseling Cell, was a resounding success. The event took place on October 10th, featuring an insightful program to raise awareness and understanding about mental health within our community. Attendees witnessed a compelling video presentation that delved into character strengths, memento distribution to honor speakers from the "Heal Out Loud" event, a thought-provoking address by our Director, and a heartwarming high tea. This event united our community in support of mental health. Stay tuned for more enriching experiences with Sunshine',
    images: [
      "/../../EventsImages/UGReality/IMG_6444.JPG",
      "/../../EventsImages/UGReality/IMG_6468.JPG",
      "/../../EventsImages/UGReality/IMG_6470.JPG",
      "/../../EventsImages/UGReality/IMG_6485.JPG",
      "/../../EventsImages/UGReality/IMG_6519.JPG",
      "/../../EventsImages/UGReality/IMG_6537.JPG",
      "/../../EventsImages/UGReality/IMG_6543.JPG",
      "/../../EventsImages/UGReality/IMG_6552.JPG",
      "/../../EventsImages/UGReality/IMG_6578.JPG",
      "/../../EventsImages/UGReality/IMG_6590.JPG",
    ],
  },
  {
    slug: "SuicidePreventionWeekTrainingSession",
    date: "September 15, 2023",
    title: "Suicide Prevention Week Training Session",
    summary:
      'In line with our commitment to student well-being, Sunshine - The Counselling Cell at IIT Hyderabad organized a vital training session on September 15th, 2023, as part of "Suicide Prevention Week." This event aimed to equip students with essential skills, covering suicide prevention techniques, distress tolerance skills, and cognitive restructuring. Our objective was to empower students with inner strength, provide evidence-based therapeutic approaches, and ensure support for those who may have difficulty seeking help. We extend our gratitude to all participants for their active engagement, fostering a caring and empathetic community at IIT Hyderabad. Stay tuned for more impactful events with Sunshine.',
    images: [
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6310.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6317.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6324.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6335.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6342.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6360.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6375.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6384.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6394.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6424.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6425.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6428.jpg",
      "/../../EventsImages/SuicidePreventionWeekTrainingSession/IMG_6432.jpg",      
    ],
  },
  {
    slug: "Wonder",
    date: "September 13, 2023",
    title: '"Wonder" Movie Screening - Mental Health Awareness Night',
    summary:
      'Sunshine, the Counseling and Mental Health Club at IIT Hyderabad, successfully hosted a special movie screening event on September 13th, 2023. The film, "Wonder," provided a heartwarming and thought-provoking cinematic experience, aimed at promoting mental health awareness and fostering a supportive community. Attendees enjoyed the movie and engaged in a meaningful post-screening discussion, creating a safe space for open dialogue on mental well-being. It was a wonderful opportunity to take a break, connect with others, and reflect on the importance of mental health in our fast-paced lives. Stay tuned for more events like this with Sunshine.',
    images: [
      "/../../EventsImages/UGReality/IMG_6444.JPG",
      "/../../EventsImages/UGReality/IMG_6468.JPG",
      "/../../EventsImages/UGReality/IMG_6470.JPG",
      "/../../EventsImages/UGReality/IMG_6485.JPG",
      "/../../EventsImages/UGReality/IMG_6519.JPG",
      "/../../EventsImages/UGReality/IMG_6537.JPG",
      "/../../EventsImages/UGReality/IMG_6543.JPG",
      "/../../EventsImages/UGReality/IMG_6552.JPG",
      "/../../EventsImages/UGReality/IMG_6578.JPG",
      "/../../EventsImages/UGReality/IMG_6590.JPG",
    ],
  },
  {
    slug: "DiscoverThePowerWithin",
    date: "September 12, 2023",
    title: '"Discover the Power Within" Interview',
    summary:
      '"Discover the Power Within" was an exceptional interview that celebrated the extraordinary qualities and strengths of our IITH community. From September 12th to September 17th, participants had the opportunity to hear personal stories of triumph, uncover their inner superpowers, gain inspirational insights, and engage in interactive Q&A sessions. The event celebrated the diverse strengths that make our IITH community special and aimed to inspire each other to tap into their inner power. As Mahatma Gandhi once said, "Strength does not come from physical capacity. It comes from an indomitable will." This event was a heartwarming journey of self-discovery and community celebration. Stay tuned for more inspiring events with us!',
    images: [
      "/../../EventsImages/UGReality/IMG_6444.JPG",
      "/../../EventsImages/UGReality/IMG_6468.JPG",
      "/../../EventsImages/UGReality/IMG_6470.JPG",
      "/../../EventsImages/UGReality/IMG_6485.JPG",
      "/../../EventsImages/UGReality/IMG_6519.JPG",
      "/../../EventsImages/UGReality/IMG_6537.JPG",
      "/../../EventsImages/UGReality/IMG_6543.JPG",
      "/../../EventsImages/UGReality/IMG_6552.JPG",
      "/../../EventsImages/UGReality/IMG_6578.JPG",
      "/../../EventsImages/UGReality/IMG_6590.JPG",
    ],
  },
  {
    slug: "HealOutLoud",
    date: "September 11, 2023",
    title: '"Heal Out Loud: Stories of Us"',
    summary:
      "'Heal Out Loud' was a remarkable event that celebrated resilience, shared stories of courage, and created hope through action. On September 11th, 2023, the IIT Hyderabad community came together to break down barriers, support one another, and nurture a compassionate and understanding environment. Attendees had the opportunity to hear powerful stories of overcoming challenges and the unbreakable human spirit. This event served as a reminder that no one is alone, and Sunshine is a supportive haven within IIT Hyderabad. Whether sharing stories or simply listening, every individual's presence was cherished and valued. Stay tuned for more empowering events with us.",
    images: [
      "/../../EventsImages/HealOutLoud/Copy of IMG_3265.jpeg",
      "/../../EventsImages/HealOutLoud/IMG_3263.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3283.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3261.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3262.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3271.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3284.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3299.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3328.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3320.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3330.JPG",
      "/../../EventsImages/HealOutLoud/IMG_3270.JPG",      
    ],
  },
  {
    slug: "ThePassionPalette",
    date: "August-September , 2023",
    title: "The Passion Palette",
    summary: "'The Passion Palette' was an event that celebrated the diverse talents and creativity within our community. It encouraged participants to showcase their unique talents through video, audio, artwork, or write-ups. By sharing their creative passions, attendees found an outlet for self-expression, experienced a sense of accomplishment, and gained stress management skills. The event highlighted the positive impact of talent expression on mental health, happiness, self-confidence, and resilience. Entries were submitted, and the best ones were featured on Sunshine's social media platforms. Stay tuned for more opportunities to express your individuality and creativity with us.",
    description: "'The Passion Palette' was an event that celebrated the diverse talents and creativity within our community. It encouraged participants to showcase their unique talents through video, audio, artwork, or write-ups. By sharing their creative passions, attendees found an outlet for self-expression, experienced a sense of accomplishment, and gained stress management skills. The event highlighted the positive impact of talent expression on mental health, happiness, self-confidence, and resilience. Entries were submitted, and the best ones were featured on Sunshine's social media platforms. Stay tuned for more opportunities to express your individuality and creativity with us.",
    images: [
      "/../../EventsImages/UGReality/IMG_6444.JPG",
      "/../../EventsImages/UGReality/IMG_6468.JPG",
      "/../../EventsImages/UGReality/IMG_6470.JPG",
      "/../../EventsImages/UGReality/IMG_6485.JPG",
      "/../../EventsImages/UGReality/IMG_6519.JPG",
      "/../../EventsImages/UGReality/IMG_6537.JPG",
      "/../../EventsImages/UGReality/IMG_6543.JPG",
      "/../../EventsImages/UGReality/IMG_6552.JPG",
      "/../../EventsImages/UGReality/IMG_6578.JPG",
      "/../../EventsImages/UGReality/IMG_6590.JPG",
    ],
  },
  {
    slug: "RealityShow",
    date: "October 19, 2023",
    title: "UG Reality Show",
    summary:
      'The Art Therapy Workshop, hosted by Sunshine, the Counseling Cell of IITH, was a resounding success. Participants engaged in a series of creative activities, including "Pass It Around", which promoted unity and diverse perspectives. The "Guided Imagery Technique" provided a unique opportunity to relax and reflect using the power of imagination, while "Mindful Eating" allowed attendees to connect with their senses and improve their relationship with food.This event, held on 19th October 2023, not only provided moments of tranquility and stress relief but also facilitated community connections within our diverse IITH community. No prior artistic talent was necessary for participation. Stay tuned for more enriching events with Sunshine. For inquiries, feel free to reach out to us.',
    images: [
      "/../../EventsImages/UGReality/IMG_6444.JPG",
      "/../../EventsImages/UGReality/IMG_6468.JPG",
      "/../../EventsImages/UGReality/IMG_6470.JPG",
      "/../../EventsImages/UGReality/IMG_6485.JPG",
      "/../../EventsImages/UGReality/IMG_6519.JPG",
      "/../../EventsImages/UGReality/IMG_6537.JPG",
      "/../../EventsImages/UGReality/IMG_6543.JPG",
      "/../../EventsImages/UGReality/IMG_6552.JPG",
      "/../../EventsImages/UGReality/IMG_6578.JPG",
      "/../../EventsImages/UGReality/IMG_6590.JPG",
    ],
  },
  {
    slug: "MHAweekevent",
    date: "SEPTEMBER 14, 2023",
    title: "Event 1: MHA week event",
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    images: [
      "/../../EventsImages/MHAweekevent/IMG20230930182150.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_181626.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_182057.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230930_181456.jpg",
      "/../../EventsImages/MHAweekevent/IMG_20230928_231402.jpg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.48.22.jpeg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.49.53.jpeg",
      "/../../EventsImages/MHAweekevent/WhatsApp Image 2022-12-05 at 10.49.55.jpeg",
    ],
  },
  {
    slug: "SuicidePreventionDay",
    date: "SEPTEMBER 14, 2023",
    title: "Event 1: Suicide Prevention Day",
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    images: [
      "/../../EventsImages/SuicidePreventionDay/IMG_20221109_120503_Greatness.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC00043.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09909.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09930.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09931.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09941.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09942.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09947.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09968.jpg",
      "/../../EventsImages/SuicidePreventionDay/DSC09988.jpg",
    ],
  },
  {
    slug: "painting",
    date: "SEPTEMBER 14, 2023",
    title: "Event 1: Painting",
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    images: [
      "/../../EventsImages/Painting/p3e3.JPG",
      "/../../EventsImages/Painting/e4p4.JPG",
      "/../../EventsImages/Painting/p7e7.JPG",
      "/../../EventsImages/Painting/p5e5.JPG",
      "/../../EventsImages/Painting/p2e2.JPG",
      "/../../EventsImages/Painting/p1e.JPG",
    ],
  },
  {
    slug: "PGPHDEvents",
    date: "September 14, 2023",
    title: "Event 1: PG-PHD Events",
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    images: [
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191301.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193453.jpg",
      "/../../EventsImages/PGPhdEvents/DSC00754.JPG",
      "/../../EventsImages/PGPhdEvents/DSC00817.JPG",
      "/../../EventsImages/PGPhdEvents/IMG_20220925_182257.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20220925_184849.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191341.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191707.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191752.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_191853.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_192006.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_192046.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_192527.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193336.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193425.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193545.jpg",
      "/../../EventsImages/PGPhdEvents/IMG_20230930_193615.jpg",
    ],
  },
  {
    slug: "DepartmentalOrientation",
    date: "September 14, 2023",
    title: "Event 1:Departmental Orientations ",
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque scelerisque dapibus dui sit amet molestie. Nam dignissim augue purus, in finibus eros commodo vitae. Donec convallis ex ut risus bibendum maximus. Proin aliquet sollicitudin dui, sed finibus ex lacinia quis. In vel mollis dolor. Fusce in magna eu sapien ornare pulvinar a in nulla. Nam rhoncus massa ut eros vulputate porta. In sagittis pellentesque tempor. Vestibulum bibendum lectus vel dolor eleifend consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nec est et sem porta pulvinar.",
    images: [
      "/../../EventsImages/DepartmentalOrientation/EE/20221109_181057.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/20221109_181524.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/20221109_191948.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109181509.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109181757.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109182025.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109184344.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109190309.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109192605.jpg",
      "/../../EventsImages/DepartmentalOrientation/EE/IMG20221109193317.jpg",
      "/../../EventsImages/DepartmentalOrientation/AI/20221111_164926.jpg",
    ],
  },
];

export default events;
